config/routes.rb
MusicAlbum::Application.routes.draw do
  get "user_sessions/new"

  resources :user_sessions
  resources :users
  resources :albums
  root :to => "user_sessions#new"
  match 'login' => "user_sessions#new",      :as => :signin
  match 'logout' => "user_sessions#destroy", :as => :signout
  match 'home' => "albums#index", :as => :home

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user

  has_attached_file :album_cover,
    :path => ":rails_root/public/album_covers/:id/:styles.:extension",
    :url => "/album_covers/:id/:style/:basename.:extension",
    :styles => {
      :thumb=> "100x100#",
      :small  => "150x150>",
      :origial => "300X300"
    }
  has_attached_file :album,
    :path => ":rails_root/public/albums/:id/:styles.:extension",
    :url => "/albums/:id/:style/:basename.:extension"
  validates_attachment_presence :album
  validates_attachment_content_type :album, :content_type => ['audio/ogg', 'audio/mp3', 'audio/mpeg']
  validates_attachment_content_type :album_cover, :content_type => ['image/jpeg','image/png','image/gif','image/jpg','image/pjpeg']
#  validates_attachment_size :album_cover, :in => 1..104857600
  validates :title, :presence => true
  validates :user, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_authentic
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name, :display_name

  #Validations
  validates :first_name, :presence => true
  validates :last_name, :presence => true
  validates :display_name, :presence => true
  validates :email, :presence => true, :uniqueness => true
  validates_format_of :email,
    :with => %r{^(?:[_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-zA-Z0-9\-\.]+)*(\.[a-z]{2,4})$}i,
    :message => "is not a valid email address.",
    :if => Proc.new {|u| not u.email.blank?}
  validates :password, :presence => true
  validates :password_confirmation, :presence => true
  validates_confirmation_of :password

  #Associations
  has_many :albums, :dependent => :destroy

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base

  def to_key
    new_record? ? nil : [ self.send(self.class.primary_key) ]
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_filter :require_user

  def index
    @albums = if params[:search].present?
      current_user.albums.find(:all, :conditions => ["title like ?", "#{params[:search]}%"])
    else
      current_user.albums
    end
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.new(params[:album])
    if @album.save
      redirect_to home_path
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def destroy
    album = Album.find(params[:id])
    album.destroy
    flash[:notice] = "Music deleted successfully"
    redirect_to home_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user_session, :current_user

  private
  def current_user_session
    logger.debug "ApplicationController::current_user_session"
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    logger.debug "ApplicationController::current_user"
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    logger.debug "ApplicationController::require_user"
    unless current_user
      store_location
      flash[:notice] = "You must be logged in to access this page"
      redirect_to new_user_session_url
      return false
    end
  end

  def require_no_user
    logger.debug "ApplicationController::require_no_user"
    if current_user
      store_location
      flash[:notice] = "You must be logged out to access this page"
      redirect_to account_url
      return false
    end
  end


    def store_location
      session[:return_to] = request.request_uri
    end

    def redirect_back_or_default(default)
      redirect_to(session[:return_to] || default)
      session[:return_to] = nil
    end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default home_path
    else
      render :action => :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default new_user_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Account created successfully"
      redirect_to home_path
    else
      render :new
    end
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/index.html.haml
- if @albums.present?
  - @albums.each do |album|
    #album
      .float_left= image_tag album.album_cover.url(:thumb, false), :width => "64", :height => "64"
      .float_left
        %div= link_to album.title, album_path(album)
        %div= link_to "Delete", album_path(album), :method => :delete

      %audio{:controls => "controls"}
        %source{:src => album.album.url, :type => album.album_content_type}
        Your browser does not support the audio element.
- else
  == No music found

app/views/albums/new.html.haml
#album_panel
  %h1 New Album

  = form_for @album, :url => {:action => "create"}, :html => { :multipart => true } do |f|
    = f.error_messages
    %div
      = f.label :title
    %div
      = f.text_field :title
    %div
      = f.label :description
    %div
      = f.text_area :description, :cols => 40, :rows => 5
    %div
      = f.label :album
    %div
      = f.file_field :album
    %div
      = f.label :album_cover
    %div
      = f.file_field :album_cover
    %div
      = f.submit "Create Album"

app/views/albums/show.html.haml
#show_album
  .float_left= image_tag @album.album_cover.url(:original, false)
  .float_left
    %div= link_to @album.title, album_path(@album)
    %div= @album.description
  %audio{:controls => "controls"}
    %source{:src => @album.album.url, :type => @album.album_content_type}
    Your browser does not support the audio element.

app/views/layouts/application.html.haml
<!doctype html>
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "width=device-width; initial-scale=1.0", :name => "viewport"}
    %title MusicAlbum
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = csrf_meta_tag
  %body
    #container
      .music
        .header
          %div.head_content.header_footer
            %div.logo.float_left
              == Music Album
            .user_links.float_right
              - if current_user.present?
                == Welcome #{current_user.display_name}
              - else
                = link_to("Signup", new_user_path)
            .clear
        .clear
        - if flash[:notice].present?
          .flash
            = flash[:notice]
        .header_menu
          .top_menu
            .active= link_to("Home", home_path)
          - if current_user.present?
            .top_menu
              .active= link_to("Add Album", new_album_path)
            .top_menu
              .active= link_to("Logout", signout_path)
            .top_menu.search
              - form_tag(home_path, :method => :get) do
                = text_field_tag :search, params[:search]
                = submit_tag "Search"
          - else
            .top_menu
              .active= link_to("Login", signin_path)
        .clear
        .content
          .home
            .home_left
              = yield
        .clear
        .footer
          .footer_content

app/views/user_sessions/new.html.haml
#login_panel
  %h1 Login

  = form_for @user_session, :url => {:action => "create"} do |f|
    = f.error_messages
    %div
      = f.label :email
    %div
      = f.text_field :email
    %div
      = f.label :password
    %div
      = f.password_field :password
    %div
      = f.submit "Login"

app/views/users/new.html.haml
#register_panel
  %h1 Signup

  = form_for @user, :url => {:action => "create"} do |f|
    = f.error_messages
    %div
      = f.label :email
    %div
      = f.text_field :email
    %div
      = f.label :display_name
    %div
      = f.text_field :display_name
    %div
      = f.label :first_name
    %div
      = f.text_field :first_name
    %div
      = f.label :last_name
    %div
      = f.text_field :last_name
    %div
      = f.label :password
    %div
      = f.password_field :password
    %div
      = f.label :password_confirmation
    %div
      = f.password_field :password_confirmation
    %div
      = f.submit "Create My Account"